# Generated by Django 5.0.6 on 2024-07-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expire_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
