# Generated by Django 5.0.6 on 2024-07-12 22:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_session_expire_timestamp'),
        ('inventory', '0007_alter_inventory_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='UserCart',
        ),
        migrations.RenameModel(
            old_name='CartItems',
            new_name='UserCartItems',
        ),
        migrations.AlterModelTable(
            name='usercart',
            table='user_cart',
        ),
        migrations.AlterModelTable(
            name='usercartitems',
            table='user_cart_items',
        ),
    ]
