# Generated by Django 5.0.6 on 2024-07-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_cart_usercart_rename_cartitems_usercartitems_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='cart_id',
            new_name='user_cart_id',
        ),
        migrations.RenameField(
            model_name='usercartitems',
            old_name='cart_id',
            new_name='user_cart_id',
        ),
    ]
