# Generated by Django 5.0.6 on 2024-07-12 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_cart_id_usercart_user_cart_id_and_more'),
        ('inventory', '0007_alter_inventory_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCart',
            fields=[
                ('guest_cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.session')),
            ],
            options={
                'db_table': 'guest_cart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GuestCartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('guest_cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.guestcart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventory')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guest_cart_items',
                'managed': True,
            },
        ),
    ]
