# Generated by Django 5.0.6 on 2024-07-14 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_session_access_token_session_refresh_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sessionID',
            field=models.CharField(db_column='sessionID', max_length=64, unique=True),
        ),
        migrations.RenameField(
            model_name='session',
            old_name='sessionID',
            new_name='sessionid',
        ),
        migrations.AlterField(
            model_name='guestcart',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.session'),
        ),
        migrations.AlterField(
            model_name='guestcartitems',
            name='guest_cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.guestcart'),
        ),
        migrations.AlterField(
            model_name='guestcartitems',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guestcartitems',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercartitems',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
