# Generated by Django 5.0.6 on 2024-07-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_guestcartitems_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcartitems',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
