# Generated by Django 5.0.6 on 2024-07-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_session_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
