# Generated by Django 5.0.6 on 2024-06-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('comic_id', models.AutoField(primary_key=True, serialize=False)),
                ('ebay_itemid', models.CharField(blank=True, db_column='ebay_itemID', max_length=64, null=True)),
                ('listing_title', models.CharField(blank=True, db_column='Listing_Title', max_length=128, null=True)),
                ('tags', models.CharField(blank=True, db_column='Tags', max_length=50, null=True)),
                ('publisher_name', models.CharField(blank=True, db_column='Publisher_Name', max_length=255, null=True)),
                ('series_name', models.CharField(blank=True, db_column='Series_Name', max_length=255, null=True)),
                ('full_title', models.CharField(blank=True, db_column='Full_Title', max_length=255, null=True)),
                ('release_date', models.CharField(blank=True, db_column='Release_Date', max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
                ('price', models.CharField(blank=True, db_column='Price', max_length=50, null=True)),
                ('picurl', models.TextField(blank=True, db_column='PicURL', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
