# Generated by Django 5.0.6 on 2024-06-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_options_inventory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='comic_id',
            new_name='item_id',
        ),
    ]
