# Generated by Django 5.0.6 on 2024-06-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_publisher_name_inventory_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='publisher',
            field=models.CharField(blank=True, db_column='publisher', max_length=255, null=True),
        ),
    ]
