# Generated by Django 5.0.6 on 2024-07-16 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='package_height',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='inventory',
            name='package_length',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='inventory',
            name='package_weight',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='inventory',
            name='package_width',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('product_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_object', models.CharField(blank=True, default='product', max_length=64, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('shippable', models.BooleanField(default=True)),
                ('tax_code', models.IntegerField(blank=True, default=99999999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
            options={
                'db_table': 'stripe_product',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='stripe_product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stripeproduct'),
        ),
    ]
