# Generated by Django 5.0.6 on 2024-07-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventory_package_height_inventory_package_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(blank=True, db_column='Price', decimal_places=2, default=9.99, max_digits=10, null=True),
        ),
    ]
