# Generated by Django 5.0.6 on 2024-07-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeproduct',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
