# Generated by Django 5.0.6 on 2024-07-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stripeproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeproduct',
            name='shippable',
            field=models.BooleanField(null=True),
        ),
    ]
