# Generated by Django 4.2.2 on 2023-09-10 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.ForeignKey(
                        db_column="id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Cart",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.BigAutoField(
                        db_column="product_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "publisher_name",
                    models.CharField(
                        blank=True, db_column="Publisher_Name", max_length=50, null=True
                    ),
                ),
                (
                    "series_name",
                    models.CharField(
                        blank=True, db_column="Series_Name", max_length=128, null=True
                    ),
                ),
                (
                    "full_title",
                    models.CharField(
                        blank=True, db_column="Full_Title", max_length=256, null=True
                    ),
                ),
                (
                    "release_date",
                    models.CharField(
                        blank=True, db_column="Release_Date", max_length=50, null=True
                    ),
                ),
                ("year", models.IntegerField(blank=True, db_column="Year", null=True)),
                (
                    "in_collection",
                    models.IntegerField(
                        blank=True, db_column="In_Collection", null=True
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, db_column="Notes", max_length=50, null=True
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, db_column="Tags", max_length=50, null=True
                    ),
                ),
                (
                    "picurl",
                    models.CharField(
                        blank=True, db_column="PicURL", max_length=128, null=True
                    ),
                ),
                (
                    "listing_title",
                    models.CharField(
                        blank=True, db_column="Listing_Title", max_length=128, null=True
                    ),
                ),
            ],
            options={
                "db_table": "product",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Product.cart"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.product",
                    ),
                ),
            ],
            options={
                "db_table": "CartItem",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="cart",
            name="cartItems",
            field=models.ManyToManyField(related_name="carts", to="Product.product"),
        ),
    ]
