# Generated by Django 4.2.2 on 2023-09-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Product", "0002_alter_cart_cartitems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cartItems",
            field=models.ManyToManyField(related_name="carts", to="Product.product"),
        ),
    ]
