# Generated by Django 4.2.2 on 2023-09-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Product", "0003_alter_cart_cartitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                db_column="Price",
                decimal_places=2,
                max_digits=13,
                null=True,
            ),
        ),
    ]
